### ISSUE TITLE
Como faco para fazer parte dessa comunidade no Github?

### ISSUE THREAD

**Issue by carneiroDotDev** [DenoBrazil/open-source#1]
Salve! 

Eu to usando o Gitlab já por alguns anos e estou perdido em como faco para 
participar de uma comunidade no Github. Com a minha primeira PR, eu automaticamente 
faco parte da cmm? ou preciso fazer algo antes de enviar uma PR?  🤔

Tmj

**Comment by LauraBeatris** [comment]
Oi @carneiroDotDev 

Você pode contribuir enviando issues ou PRs nos nossos repositórios. 
Eu aconselho por agora, focar no fórum pois os outros ainda estão em processo de planejamento. 

Ah, e você já contribuiu por mandar estar mandando essa issue. 
Valeu <3
